### ISSUE TITLE
Remove unneeded redirection (PDK progress indicator)

### ISSUE THREAD

**Issue by bittner** [edestecd/puppet-software#20]
The [redirection of output](https://github.com/edestecd/puppet-software/blob/master/.travis.yml#L14) to `stderr` can now simply be removed, i.e. use code like this:

```yaml
- stage: validate
  script: pdk validate

- stage: test
  script: pdk test unit
```

See https://github.com/puppetlabs/pdk/issues/323#issuecomment-388158858 for reference.
